### ISSUE TITLE
Field Contents Is Not Saved When Form Submitted

### ISSUE THREAD

**Issue by andrewturner** [soulseekah/gravityformstimesheet#2]
Wordpress v4.4.2
Gravity Forms v1.9.16

Field is displayed and values can be validated, however when submitted, no values are parsed through to the save_timesheet_input method (checked by logging all parameters of function) - timesheet field is not passed to this method.

No values saved in DB, and associated errors like so

![formerrors](https://cloud.githubusercontent.com/assets/60941/12885296/f88573d6-ceb8-11e5-8926-5bd21f929b41.PNG)

**Comment by soulseekah** [comment]
This was a bug in Gravity Forms 1.9.15 or 1.9.16 and gone in 1.9.16.2 update.

> ---
> 
> Version 1.9.16.2
> - Updated form view count and lead count so that they are cached to improve performance.
> - **Fixed an issue which prevented the gform_save_field_value hook running for custom field types when the input value was an array.**
> - API: Fixed an issue with a logging statement for the Web API.
> 
> ---
> 
> Version 1.9.16.1
>     - Fixed an issue which caused merge tags added by autocomplete to be lost on form save.

Which is exactly what we had... thanks for reporting and trying with the newest version. Closing as solved.
