### ISSUE TITLE
Submissions Blank

### ISSUE THREAD

**Issue by MHowardAR** [soulseekah/gravityformstimesheet#3]
I have uploaded and activated the plugin and it works beautifully on screen. But when I click submit it doesn't actually send/post the time sheet data that was entered. Any ideas?

Here is an example pasted from the email (you'll see the form captured a name but not the date, time in or time out that were entered):
Name
    Donald Duck
Timesheet

Date    Check in    Check out   Comment
Total entries: 0    Total time: 00:00

**Comment by soulseekah** [comment]
What version of Gravity Forms are you using?

Sounds like this issue here https://github.com/soulseekah/gravityformstimesheet/issues/2 which was a bug in Gravity Forms.

**Comment by MHowardAR** [comment]
Thanks for your response. Here is the install information.

Installation Status

PHP Version 5.4.45-0+deb7u2 
MySQL Version   5.5.47  
WordPress Version   4.4.2  
Gravity Forms Version   1.9.16

**Comment by soulseekah** [comment]
Did you read the #2 issue?

**Comment by MHowardAR** [comment]
I looked at the issue you referenced and I'll try again after update of Gravity Forms.

Thanks again!

**Comment by MHowardAR** [comment]
Yep. Updating Gravity Forms took care of the issue!
