### ISSUE TITLE
No longer supported.

### ISSUE THREAD

**Issue by nixonthekat** [soulseekah/gravityformstimesheet#4]
Hey Guys, Great plugin however it's no longer supported.

On submitting a time entry I get in return..

`Warning: array_chunk() expects parameter 1 to be array, string given in wp-content\plugins\gravityformstimesheet.php on line 519`

`Warning: Invalid argument supplied for foreach() in wp-content\plugins\gravityformstimesheet.php on line`

**Comment by nixonthekat** [comment]
My best guess is the data is no longer getting passed through your jquery but I could be wrong. Cheers.

**Comment by soulseekah** [comment]
What version of GF are you using?

Please see #2 and #3 and let me know if that helped.

**Comment by nixonthekat** [comment]
Thank you for the fast response,

I'm using 1.9.9.4.

 i'll look into those.

**Comment by soulseekah** [comment]
Update to Gravity Forms 1.9.16.2 or later as per #2 and #3

**Comment by nixonthekat** [comment]
Just updated to 1.9.16 (there's no available updates beyond that) and i'm still receiving this error.

**Comment by soulseekah** [comment]
Did you remove all the leads and try submitting again?

Also deactivate all plugins except this one and GF, set theme to a default one and test again.

**Comment by nixonthekat** [comment]
I had this working before I updated however it was still giving me php errors, had it working as in it was submitting the data but still saying no data was being passed through on the entries index list until you viewed the entry single. 
1. Left only your plugin and Gravity forms running.
2. Switched theme back to default wordpress theme.
3. Deleted leads and made a new one.

and no luck still, still not processing the data.

If it helps, diagnose the problem..
1. No-Conflict mode is set to off.
2. Background updates set to on.
3. PHP: 5.5.15, MySQL: 5.6.20, WordPress: 4.4.2, Gravity Forms: 1.9.16
4. Enable access to Gravity Forms json API is disabled.
5. The Timesheet field is set to required.
6. Ajax is enabled.
7. No console errors.

**Comment by soulseekah** [comment]
Like I said you need 1.9.16.2 since plain 1.9.16 has a bug in it that doesn't allow processing of data, see #2 and #3

**Comment by nixonthekat** [comment]
Ah, I found it on their website seems they haven't launched it within the plugin updates. Thanks for the support that fixed it. For future people seeing this issue, https://www.gravityhelp.com/downloads/
